// n8n Runtime Configuration — pure helpers shared by the Admin System
// Settings page (src/pages/admin/AdminSystemSettings.jsx) and the API
// (api/system-settings.js, api/_lib/inboundWebhookBase.js). No DOM, no I/O.
//
// Storage contract (UNCHANGED): system_settings keys, one value each, per
// Supabase project (DEV/PROD each have their own rows):
//   main_inbound_webhook_url, human_reply_webhook_url,
//   evolution_api_gateway_workflow_url,
//   ai_agent_core_workflow_url + ai_agent_core_workflow_id,
//   inbound_media_core_workflow_url + inbound_media_core_workflow_id.
// The *_workflow_id keys stay the runtime values the n8n parent workflows
// execute; the admin now enters only the Workflow URL and the ID is
// extracted from it, so the two can never disagree.

export const SETTINGS_KEYS = [
  "main_inbound_webhook_url",
  "human_reply_webhook_url",
  "evolution_api_gateway_workflow_url",
  "ai_agent_core_workflow_url",
  "ai_agent_core_workflow_id",
  "inbound_media_core_workflow_url",
  "inbound_media_core_workflow_id",
];

export const WEBHOOK_SETTINGS = ["main_inbound_webhook_url", "human_reply_webhook_url", "evolution_api_gateway_workflow_url"];

// Core workflows: the URL is the admin input, the ID is derived.
export const WORKFLOW_PAIRS = [
  { urlKey: "ai_agent_core_workflow_url", idKey: "ai_agent_core_workflow_id" },
  { urlKey: "inbound_media_core_workflow_url", idKey: "inbound_media_core_workflow_id" },
];

// ---- Main Inbound Flow base -------------------------------------------------
// https only, no query / fragment / credentials, path contains /webhook/
// and ends with /inbound; trailing slashes stripped. Host NOT restricted.
export function normalizeInboundWebhookBase(value) {
  if (typeof value !== "string") return null;
  const raw = value.trim();
  if (!raw || /\s/.test(raw)) return null;
  let url;
  try {
    url = new URL(raw);
  } catch {
    return null;
  }
  if (url.protocol !== "https:") return null;
  if (url.username || url.password) return null;
  if (url.search || url.hash || raw.includes("?") || raw.includes("#")) return null;
  const path = url.pathname.replace(/\/+$/, "");
  if (!path.includes("/webhook/") || !path.endsWith("/inbound")) return null;
  return `${url.origin}${path}`;
}

// ---- n8n Workflow URL -> Workflow ID -----------------------------------------
// n8n editor URLs are https://<host>[/<path-prefix>]/workflow/<id>, optionally
// followed by /<execution-id>, /executions, a query (?projectId=…) or a
// fragment. n8n workflow IDs are alphanumeric (16 chars as generated by n8n,
// e.g. MhWmT2jdYQeqMBEj); 8–64 accepted for imported IDs.
// Returns { ok: true, id, url } with url canonicalized to
// <origin><prefix>/workflow/<id>, or { ok: false, error }.
const WORKFLOW_ID_RE = /^[A-Za-z0-9]{8,64}$/;

export function extractN8nWorkflowId(value) {
  if (typeof value !== "string" || !value.trim()) return { ok: false, error: "empty" };
  const raw = value.trim();
  if (/\s/.test(raw)) return { ok: false, error: "invalid_url" };
  let url;
  try {
    url = new URL(raw);
  } catch {
    return { ok: false, error: "invalid_url" };
  }
  if (url.protocol !== "https:") return { ok: false, error: "https_required" };
  if (url.username || url.password) return { ok: false, error: "invalid_url" };
  const match = url.pathname.match(/^(.*?)\/workflow\/([^/]+)(?:\/.*)?$/);
  if (!match) return { ok: false, error: "no_workflow_path" };
  const [, prefix, id] = match;
  if (!WORKFLOW_ID_RE.test(id)) return { ok: false, error: "invalid_workflow_id" };
  return { ok: true, id, url: `${url.origin}${prefix}/workflow/${id}` };
}

// ---- Form diff -----------------------------------------------------------------
// saved  : { key: storedValue } (as returned by GET /api/system-settings)
// drafts : { key: editedValue } for rows in edit mode (webhook keys and the
//          *_workflow_url keys only — IDs are never edited directly)
// Returns { changes, errors }:
//   changes: the exact keys to POST (workflow URL changes always include
//            the matching extracted ID);
//   errors : { key: errorCode } — saving is blocked while non-empty.
// Empty values are never sent (the API never clears a stored value).
export function computeSettingsChanges(saved = {}, drafts = {}) {
  const changes = {};
  const errors = {};
  const cur = (k) => (typeof saved[k] === "string" ? saved[k].trim() : "");

  for (const key of WEBHOOK_SETTINGS) {
    if (drafts[key] === undefined) continue;
    const v = String(drafts[key] ?? "").trim();
    if (v === cur(key)) continue;
    if (!v) {
      errors[key] = "empty";
      continue;
    }
    if (key === "main_inbound_webhook_url") {
      const n = normalizeInboundWebhookBase(v);
      if (!n) {
        errors[key] = "invalid_inbound_base";
        continue;
      }
      if (n !== cur(key)) changes[key] = n;
      continue;
    }
    let ok = false;
    try {
      const u = new URL(v);
      ok = u.protocol === "https:" || u.protocol === "http:";
    } catch {
      ok = false;
    }
    if (!ok) {
      errors[key] = "invalid_url";
      continue;
    }
    changes[key] = v;
  }

  for (const { urlKey, idKey } of WORKFLOW_PAIRS) {
    if (drafts[urlKey] === undefined) continue;
    const v = String(drafts[urlKey] ?? "").trim();
    if (v === cur(urlKey) && extractN8nWorkflowId(v).id === cur(idKey)) continue;
    if (!v) {
      errors[urlKey] = "empty";
      continue;
    }
    const ex = extractN8nWorkflowId(v);
    if (!ex.ok) {
      errors[urlKey] = ex.error;
      continue;
    }
    if (ex.url !== cur(urlKey) || ex.id !== cur(idKey)) {
      changes[urlKey] = ex.url;
      changes[idKey] = ex.id;
    }
  }

  return { changes, errors };
}

// Stored URL and ID disagree (legacy data entered before IDs were derived).
export function isWorkflowPairOutOfSync(saved = {}, { urlKey, idKey }) {
  const url = typeof saved[urlKey] === "string" ? saved[urlKey].trim() : "";
  const id = typeof saved[idKey] === "string" ? saved[idKey].trim() : "";
  if (!url) return false;
  const ex = extractN8nWorkflowId(url);
  return !ex.ok || ex.id !== id;
}

// Vercel's own environment (process.env.VERCEL_ENV) -> label. No new source
// of truth: DEV = develop -> Preview, PROD = main -> Production.
export function environmentLabel(vercelEnv) {
  if (vercelEnv === "production") return "PROD";
  if (vercelEnv === "preview") return "DEV";
  if (vercelEnv === "development") return "LOCAL";
  return null;
}
